CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE}

USE ${MYSQL_DATABASE}

ALTER USER 'root'@${MYSQL_HOST} IDENTIFIED BY ${MYSQL_ROOT_PASSWORD};

CREATE USER IF NOT EXISTS ${MYSQL_USER}@${MYSQL_HOST} IDENTIFIED BY ${MYSQL_PASSWORD};

GRANT ALL PRIVILEGES ON userdb.* TO ${MYSQL_USER}@${MYSQL_HOST};

FLUSH PRIVILEGES;